EXCEPTION IN (D:/Python/PythonProjects/ParkingCounter/main.py, LINE 44 "errorChecksum += utility.getImageFromRazbery(baseUrlRazberyPi)"): Failed to parse: http:192.168.100.12:5000___2016-02-28 00:09:25.510000
EXCEPTION IN (D:/Python/PythonProjects/ParkingCounter/main.py, LINE 44 "errorChecksum += utility.getImageFromRazbery(baseUrlRazberyPi)"): Failed to parse: http:192.168.100.12:5000___2016-02-28 00:12:05.064000
EXCEPTION IN (D:/Python/PythonProjects/ParkingCounter/main.py, LINE 43 "errorChecksum += utility.getImageFromRazbery(baseUrlRazberyPi)"): ('Connection aborted.', error(10061, 'No connection could be made because the target machine actively refused it'))___2016-02-28 00:13:35.605000
EXCEPTION IN (C:/Users/Ivan/PycharmProjects/ParkingCounter/ParkingCounter/main.py, LINE 43 "errorChecksum += utility.getImageFromRazbery(baseUrlRazberyPi)"): ('Connection aborted.', error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))___2016-03-06 19:13:14.737000
EXCEPTION IN (C:/Users/Ivan/PycharmProjects/ParkingCounter/ParkingCounter/main.py, LINE 45 "errorChecksum += utility.getImageFromRaspberry(baseUrlRazberyPi)"): ('Connection aborted.', error(10061, 'No connection could be made because the target machine actively refused it'))___2016-04-23 01:01:31.699000
